spring:
  datasource:
    username: celk
    url: jdbc:postgresql://localhost:5432/db_teste
    password: celk
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create-drop
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  server:
    port: 8080
