spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/db_teste
    username: celk
    password: celk
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  main:
    allow-bean-definition-overriding: true

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

app-config:

  application:
    url: http://localhost:8081
    swagger-url: ${app-config.application.url}/swagger-ui.html

  oauth-clients:
    frn-auth-api:
      client: frm-auth-api-client
      secret: frm-auth-api-secret
    frm-api:
      client: frm-api-client
      secret: frm-api-secret

  services:
    frm-auth-api:
      url: http://localhost:8080

    frm-api:
      url: http://localhost:8081

security:
  oauth2:
    resource:
      filter-order: 3

server:
  port: 8081

